sudo: false

# os:
#   - osx
#   - linux
#   - windows

language: node_js

node_js:
  - lts/*

notifications:
  email:
    on_success: never
    on_failure: change<% if (features.includes('coverage')) { %>

before_script:
  - yarn global add nyc codecov<% } %>

script:
  - yarn lint
  - yarn test<% if (features.includes('coverage')) { %>

after_script:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov<% } %>
