sudo: false

os:
  - osx
  - windows
  - linux

language: node_js

node_js:
  - lts/*
  - node

cache:
  yarn: true

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - yarn test
